{"error": "ERREUR: 'FastClashDetector' object has no attribute 'detect_clashes'\nTraceback (most recent call last):\n  File \"C:\\Users\\wiemb\\Desktop\\flask-ifc-clashdetection\\app\\routes.py\", line 84, in process_clash_detection\n    clashes = detector.detect_clashes()\nAttributeError: 'FastClashDetector' object has no attribute 'detect_clashes'\n", "status": "failed"}